name: ROS Courses
description: "Courseware for ROS and robotics courses"

baseurl: https://tfoote.github.io/design
repo: https://github.com/tfoote/design

oauth_client_id: efa6dd8eae9106381720

permalink: pretty

markdown: kramdown
pygments: true

exclude:
 - CNAME
 - config.json
 - Gemfile
 - LICENSE
 - README.md
